dream89_main:
    resource: "@Dream89MainBundle/Controller/"
    type:     annotation
    prefix:   /

rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api

dream89_main_get_favorites:
   path: /api/v1/favorites
   defaults: {_controller: Dream89MainBundle:Rest:getFavorites }
   methods: [GET]

dream89_main_get_favorite:
   path: /api/v1/favorites/{favoriteItem}
   defaults: {_controller: Dream89MainBundle:Rest:getFavorite }
   methods: [GET]

dream89_main_delete_favorite:
   path: /api/v1/favorites/{favoriteItem}
   defaults: {_controller: Dream89MainBundle:Rest:delete }
   methods: [POST, DELETE]

dream89_main_update_favorite:
   path: /api/v1/favorites/{favoriteItem}
   defaults: {_controller: Dream89MainBundle:Rest:update }
   methods: [POST, PUT]

dream89_main_create_favorite:
   path: /api/v1/favorites
   defaults: {_controller: Dream89MainBundle:Rest:create }
   methods: [POST]
